import {
  File,
  FileCode,
  FileJson,
  FileText,
  FileImage,
  FileArchive,
  FileTerminal,
  Settings,
  type LucideIcon,
} from "lucide-react";

const ICONS_BY_EXTENSION: Record<string, LucideIcon> = {
  ts: FileCode,
  tsx: FileCode,
  js: FileCode,
  jsx: FileCode,
  mjs: FileCode,
  cjs: FileCode,
  rs: FileCode,
  py: FileCode,
  go: FileCode,
  rb: FileCode,
  java: FileCode,
  c: FileCode,
  h: FileCode,
  cpp: FileCode,
  hpp: FileCode,
  cs: FileCode,
  swift: FileCode,
  kt: FileCode,
  php: FileCode,
  html: FileCode,
  css: FileCode,
  scss: FileCode,
  less: FileCode,
  vue: FileCode,
  svelte: FileCode,
  sql: FileCode,
  json: FileJson,
  jsonc: FileJson,
  md: FileText,
  mdx: FileText,
  txt: FileText,
  log: FileText,
  png: FileImage,
  jpg: FileImage,
  jpeg: FileImage,
  gif: FileImage,
  svg: FileImage,
  webp: FileImage,
  ico: FileImage,
  zip: FileArchive,
  tar: FileArchive,
  gz: FileArchive,
  sh: FileTerminal,
  zsh: FileTerminal,
  bash: FileTerminal,
  ps1: FileTerminal,
  toml: Settings,
  yaml: Settings,
  yml: Settings,
  ini: Settings,
  conf: Settings,
  lock: Settings,
};

/** Pick a Lucide icon for a filename based on its extension. */
export function iconForFile(fileName: string): LucideIcon {
  const extension = fileName.split(".").pop()?.toLowerCase() ?? "";
  return ICONS_BY_EXTENSION[extension] ?? File;
}
