//! Project-wide text search, built on ripgrep's own crates (`ignore` for
//! the gitignore-aware parallel walk, `grep-searcher`/`grep-regex` for
//! matching) rather than shelling out to an `rg` binary — so search works
//! on every machine with nothing extra installed.
//!
//! Results stream to the frontend in batches over `search:results`
//! events; `search:done` closes a search. Each search gets an id from a
//! shared generation counter, and worker threads abandon the walk the
//! moment a newer search starts.

use grep_matcher::Matcher;
use grep_regex::{RegexMatcher, RegexMatcherBuilder};
use grep_searcher::sinks::UTF8;
use grep_searcher::{BinaryDetection, SearcherBuilder};
use ignore::{WalkBuilder, WalkState};
use serde::{Deserialize, Serialize};
use std::sync::atomic::{AtomicU64, AtomicUsize, Ordering};
use std::sync::mpsc::RecvTimeoutError;
use std::sync::Arc;
use std::time::Duration;
use tauri::{AppHandle, Emitter, State};

/// Stop after this many matches — a too-broad query on a big repo should
/// not flood the UI.
const MATCH_LIMIT: usize = 500;
const BATCH_SIZE: usize = 50;
const BATCH_FLUSH_INTERVAL: Duration = Duration::from_millis(60);

pub struct SearchState(pub Arc<AtomicU64>);

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum SearchMatchKind {
    /// A file's name matches the query (shown first in the UI).
    File,
    /// A folder's name matches the query (shown first in the UI).
    Folder,
    /// A line inside a file matches.
    Content,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchMatch {
    pub path: String,
    pub line_number: u64,
    pub preview: String,
    pub kind: SearchMatchKind,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct SearchBatch {
    search_id: u64,
    matches: Vec<SearchMatch>,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct SearchDone {
    search_id: u64,
    total: usize,
    limit_hit: bool,
}

/// List every file in the workspace for quick-open (Cmd+P). Uses the
/// same gitignore-aware walk as search (skips hidden dirs, node_modules,
/// etc.), returning absolute paths. Capped so a huge repo can't stall.
#[tauri::command]
pub fn list_workspace_files(root: String) -> Result<Vec<String>, String> {
    const FILE_LIMIT: usize = 20000;
    let mut files = Vec::new();
    for result in WalkBuilder::new(&root).build() {
        if files.len() >= FILE_LIMIT {
            break;
        }
        let Ok(entry) = result else { continue };
        if entry.file_type().is_some_and(|kind| kind.is_file()) {
            files.push(entry.path().to_string_lossy().into_owned());
        }
    }
    Ok(files)
}

/// The query is treated as literal text, not a regex.
fn escape_regex(literal: &str) -> String {
    let mut escaped = String::with_capacity(literal.len() * 2);
    for character in literal.chars() {
        if r"\.+*?()|[]{}^$#&-~".contains(character) {
            escaped.push('\\');
        }
        escaped.push(character);
    }
    escaped
}

/// How a query matches (the search panel's toggles).
#[derive(Deserialize, Default, Clone, Copy)]
#[serde(rename_all = "camelCase", default)]
pub struct SearchOptions {
    /// `None` = smart case (sensitive only if the query has uppercase).
    case_sensitive: Option<bool>,
    whole_word: bool,
    is_regex: bool,
}

/// One matcher for content *and* names, honoring the options.
fn build_matcher(query: &str, options: SearchOptions) -> Result<RegexMatcher, String> {
    let case_insensitive = match options.case_sensitive {
        Some(sensitive) => !sensitive,
        None => !query.chars().any(|character| character.is_uppercase()),
    };
    let pattern = if options.is_regex {
        query.to_string()
    } else {
        escape_regex(query)
    };
    RegexMatcherBuilder::new()
        .case_insensitive(case_insensitive)
        .word(options.whole_word)
        .build(&pattern)
        .map_err(|error| format!("Invalid search pattern: {error}"))
}

/// Kick off a streaming search. The id is generated by the *frontend*
/// (monotonically increasing) so the store knows it before any result
/// batch can possibly arrive — results racing ahead of the invoke
/// response must never be dropped as stale.
#[tauri::command]
pub fn search_workspace(
    app: AppHandle,
    state: State<SearchState>,
    root: String,
    query: String,
    search_id: u64,
    options: Option<SearchOptions>,
) -> Result<(), String> {
    // Starting (or clearing) a search invalidates the previous one.
    state.0.store(search_id, Ordering::SeqCst);

    if query.trim().is_empty() {
        let _ = app.emit(
            "search:done",
            SearchDone {
                search_id,
                total: 0,
                limit_hit: false,
            },
        );
        return Ok(());
    }

    let matcher = build_matcher(&query, options.unwrap_or_default())?;

    let generation = state.0.clone();
    let total_matches = Arc::new(AtomicUsize::new(0));
    let (match_sender, match_receiver) = std::sync::mpsc::channel::<SearchMatch>();

    // Collector thread: batches matches into events so the UI gets a few
    // updates per second instead of one event per match.
    let collector_app = app.clone();
    let collector_total = total_matches.clone();
    std::thread::spawn(move || {
        let mut batch: Vec<SearchMatch> = Vec::new();
        loop {
            match match_receiver.recv_timeout(BATCH_FLUSH_INTERVAL) {
                Ok(search_match) => {
                    batch.push(search_match);
                    if batch.len() >= BATCH_SIZE {
                        let _ = collector_app.emit(
                            "search:results",
                            SearchBatch {
                                search_id,
                                matches: std::mem::take(&mut batch),
                            },
                        );
                    }
                }
                Err(RecvTimeoutError::Timeout) => {
                    if !batch.is_empty() {
                        let _ = collector_app.emit(
                            "search:results",
                            SearchBatch {
                                search_id,
                                matches: std::mem::take(&mut batch),
                            },
                        );
                    }
                }
                Err(RecvTimeoutError::Disconnected) => {
                    // Walk finished; flush what's left and close out.
                    if !batch.is_empty() {
                        let _ = collector_app.emit(
                            "search:results",
                            SearchBatch {
                                search_id,
                                matches: std::mem::take(&mut batch),
                            },
                        );
                    }
                    let total = collector_total.load(Ordering::Relaxed);
                    let _ = collector_app.emit(
                        "search:done",
                        SearchDone {
                            search_id,
                            total: total.min(MATCH_LIMIT),
                            limit_hit: total >= MATCH_LIMIT,
                        },
                    );
                    break;
                }
            }
        }
    });

    // Name walk: a separate, readdir-only traversal that sees *every*
    // entry — files and folders, gitignored or hidden — so "node_modules"
    // is findable by name even though content search rightly skips it.
    // It yields the names of heavy/hidden directories without descending
    // into them, so it stays fast on any repo.
    {
        let name_sender = match_sender.clone();
        let name_generation = generation.clone();
        let name_total = total_matches.clone();
        let name_root = root.clone();
        let name_matcher = matcher.clone();
        std::thread::spawn(move || {
            const NO_DESCEND: &[&str] = &[
                "node_modules",
                "target",
                "dist",
                "build",
                "__pycache__",
                "venv",
            ];
            const MAX_ENTRIES: usize = 100_000;
            let mut pending = vec![std::path::PathBuf::from(&name_root)];
            let mut visited = 0usize;
            while let Some(directory) = pending.pop() {
                if name_generation.load(Ordering::Relaxed) != search_id
                    || name_total.load(Ordering::Relaxed) >= MATCH_LIMIT
                    || visited >= MAX_ENTRIES
                {
                    break;
                }
                let Ok(reader) = std::fs::read_dir(&directory) else {
                    continue;
                };
                for entry in reader.flatten() {
                    visited += 1;
                    let entry_name =
                        entry.file_name().to_string_lossy().into_owned();
                    let is_directory = entry
                        .file_type()
                        .map(|kind| kind.is_dir())
                        .unwrap_or(false);
                    // Same matcher as content, so the case / whole-word /
                    // regex toggles apply to names too.
                    let name_matches = name_matcher
                        .is_match(entry_name.as_bytes())
                        .unwrap_or(false);
                    if name_matches
                        && name_total.fetch_add(1, Ordering::Relaxed)
                            < MATCH_LIMIT
                    {
                        let _ = name_sender.send(SearchMatch {
                            path: entry.path().to_string_lossy().into_owned(),
                            line_number: 0,
                            preview: entry_name.clone(),
                            kind: if is_directory {
                                SearchMatchKind::Folder
                            } else {
                                SearchMatchKind::File
                            },
                        });
                    }
                    if is_directory
                        && !entry_name.starts_with('.')
                        && !NO_DESCEND.contains(&entry_name.as_str())
                    {
                        pending.push(entry.path());
                    }
                }
            }
        });
    }

    // Content walker thread pool: gitignore-aware parallel traversal.
    std::thread::spawn(move || {
        let walker = WalkBuilder::new(&root).build_parallel();
        walker.run(|| {
            let matcher = matcher.clone();
            let match_sender = match_sender.clone();
            let generation = generation.clone();
            let total_matches = total_matches.clone();
            Box::new(move |entry_result| {
                // A newer search started, or we have enough — stop walking.
                if generation.load(Ordering::Relaxed) != search_id
                    || total_matches.load(Ordering::Relaxed) >= MATCH_LIMIT
                {
                    return WalkState::Quit;
                }
                let Ok(entry) = entry_result else {
                    return WalkState::Continue;
                };
                if !entry.file_type().is_some_and(|kind| kind.is_file()) {
                    return WalkState::Continue;
                }

                let file_path = entry.path().to_path_buf();
                let path_string = file_path.to_string_lossy().into_owned();
                let mut searcher = SearcherBuilder::new()
                    .binary_detection(BinaryDetection::quit(0))
                    .line_number(true)
                    .build();
                let _ = searcher.search_path(
                    &matcher,
                    &file_path,
                    UTF8(|line_number, line| {
                        if total_matches.fetch_add(1, Ordering::Relaxed) >= MATCH_LIMIT {
                            return Ok(false); // stop searching this file
                        }
                        let preview: String =
                            line.trim_end().chars().take(250).collect();
                        let _ = match_sender.send(SearchMatch {
                            path: path_string.clone(),
                            line_number,
                            preview,
                            kind: SearchMatchKind::Content,
                        });
                        Ok(true)
                    }),
                );
                WalkState::Continue
            })
        });
        // All sender clones drop here, disconnecting the collector.
    });

    Ok(())
}

/// Every file containing at least one match — for "Replace All", which
/// must reach all matching files, not just the (capped) result list.
#[tauri::command]
pub async fn files_with_matches(
    root: String,
    query: String,
    options: Option<SearchOptions>,
) -> Result<Vec<String>, String> {
    const FILE_LIMIT: usize = 10_000;
    if query.is_empty() {
        return Ok(Vec::new());
    }
    let matcher = build_matcher(&query, options.unwrap_or_default())?;
    tokio::task::spawn_blocking(move || {
        let mut files = Vec::new();
        let mut searcher = SearcherBuilder::new()
            .binary_detection(BinaryDetection::quit(0))
            .build();
        for entry in WalkBuilder::new(&root).build() {
            if files.len() >= FILE_LIMIT {
                break;
            }
            let Ok(entry) = entry else { continue };
            if !entry.file_type().is_some_and(|kind| kind.is_file()) {
                continue;
            }
            let mut found = false;
            let _ = searcher.search_path(
                &matcher,
                entry.path(),
                UTF8(|_, _| {
                    found = true;
                    Ok(false) // one match is enough
                }),
            );
            if found {
                files.push(entry.path().to_string_lossy().into_owned());
            }
        }
        files
    })
    .await
    .map_err(|error| format!("Search failed: {error}"))
}

/// One-shot (non-streaming) content search, used by the AI agent's
/// `search` tool. Same gitignore-aware walk and smart-case matching as
/// the streaming search, but returns results directly. `is_regex` lets
/// the agent use patterns; otherwise the query is literal.
#[tauri::command]
pub fn search_text(
    root: String,
    query: String,
    is_regex: Option<bool>,
    max_results: Option<usize>,
) -> Result<Vec<SearchMatch>, String> {
    if query.is_empty() {
        return Ok(Vec::new());
    }
    let limit = max_results.unwrap_or(100).clamp(1, 1000);
    let case_insensitive = !query.chars().any(|character| character.is_uppercase());
    let pattern = if is_regex.unwrap_or(false) {
        query.clone()
    } else {
        escape_regex(&query)
    };
    let matcher = RegexMatcherBuilder::new()
        .case_insensitive(case_insensitive)
        .build(&pattern)
        .map_err(|error| format!("Invalid search pattern: {error}"))?;

    let mut results: Vec<SearchMatch> = Vec::new();
    let mut searcher = SearcherBuilder::new()
        .binary_detection(BinaryDetection::quit(0))
        .line_number(true)
        .build();
    for entry in WalkBuilder::new(&root).build() {
        if results.len() >= limit {
            break;
        }
        let Ok(entry) = entry else { continue };
        if !entry.file_type().is_some_and(|kind| kind.is_file()) {
            continue;
        }
        let path_string = entry.path().to_string_lossy().into_owned();
        let _ = searcher.search_path(
            &matcher,
            entry.path(),
            UTF8(|line_number, line| {
                if results.len() >= limit {
                    return Ok(false);
                }
                results.push(SearchMatch {
                    path: path_string.clone(),
                    line_number,
                    preview: line.trim_end().chars().take(300).collect(),
                    kind: SearchMatchKind::Content,
                });
                Ok(true)
            }),
        );
    }
    Ok(results)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn search_text_literal_regex_and_limit() {
        let dir = std::env::temp_dir().join(format!("sable-search-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("a.txt"), "foo(bar)\nFoo baz\nnothing\n").unwrap();
        std::fs::write(dir.join("b.txt"), "foo again\n").unwrap();
        let root = dir.to_string_lossy().into_owned();

        // Literal: parentheses are not regex syntax.
        let hits = search_text(root.clone(), "foo(bar)".into(), None, None).unwrap();
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].line_number, 1);

        // Smart case: lowercase query matches "Foo" too.
        let hits = search_text(root.clone(), "foo".into(), None, None).unwrap();
        assert_eq!(hits.len(), 3);

        // Uppercase query is case-sensitive.
        let hits = search_text(root.clone(), "Foo".into(), None, None).unwrap();
        assert_eq!(hits.len(), 1);

        let hits = search_text(root.clone(), r"ba[rz]".into(), Some(true), None).unwrap();
        assert_eq!(hits.len(), 2);

        let hits = search_text(root.clone(), "foo".into(), None, Some(2)).unwrap();
        assert_eq!(hits.len(), 2);

        assert!(search_text(root.clone(), "(".into(), Some(true), None).is_err());

        // Options: whole word / explicit case / regex, via the shared matcher.
        let whole = build_matcher("foo", SearchOptions { whole_word: true, ..Default::default() }).unwrap();
        assert!(whole.is_match(b"foo(bar)").unwrap());
        assert!(!whole.is_match(b"foobar").unwrap());
        let sensitive = build_matcher("foo", SearchOptions { case_sensitive: Some(true), ..Default::default() }).unwrap();
        assert!(!sensitive.is_match(b"Foo baz").unwrap());
        let insensitive = build_matcher("Foo", SearchOptions { case_sensitive: Some(false), ..Default::default() }).unwrap();
        assert!(insensitive.is_match(b"foo again").unwrap());

        let runtime = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
        let mut files = runtime
            .block_on(files_with_matches(root, "baz".into(), None))
            .unwrap();
        files.sort();
        assert_eq!(files.len(), 1);
        assert!(files[0].ends_with("a.txt"));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
